#!/usr/bin/env bun
/**
 * Generate the champion catalog from downloaded assets + CommunityDragon API.
 *
 * Usage:
 *   bun run scripts/generate-champion-catalog.ts
 *
 * Output:
 *   packages/shared/src/champions/catalog.ts
 */

import { readdir } from 'fs/promises'
import { join } from 'path'

// --- Config ---

const ASSETS_DIR = join(import.meta.dir, '..', 'assets', 'lol', 'champions')
const OUTPUT_FILE = join(
  import.meta.dir,
  '..',
  'packages',
  'shared',
  'src',
  'champions',
  'catalog.ts',
)
const CDRAGON_BASE =
  'https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1'

// --- Types ---

interface CDragonChampionSummary {
  id: number
  name: string
  alias: string
}

interface CDragonChampionData {
  id: number
  name: string
  alias: string
  skins: { id: number; name: string; isBase: boolean }[]
}

interface CatalogSkin {
  id: string
  name: string
  isBase: boolean
}

interface CatalogEntry {
  alias: string
  name: string
  id: number
  skins: CatalogSkin[]
}

// --- Helpers ---

async function fetchJSON<T>(url: string): Promise<T> {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`)
  return res.json()
}

async function pooled<T>(
  items: T[],
  concurrency: number,
  fn: (item: T, index: number) => Promise<void>,
): Promise<void> {
  let index = 0
  const workers = Array.from({ length: concurrency }, async () => {
    while (index < items.length) {
      const i = index++
      await fn(items[i], i)
    }
  })
  await Promise.all(workers)
}

// --- Main ---

async function main() {
  console.log('Scanning asset directories...')

  // 1. List all champion folders that exist locally
  const localDirs = await readdir(ASSETS_DIR)
  const localAliases = new Set(localDirs.filter((d) => !d.startsWith('.')))

  console.log(`Found ${localAliases.size} local champion directories\n`)

  // 2. Fetch champion list from CommunityDragon
  console.log('Fetching champion list from CommunityDragon...')
  const champions = await fetchJSON<CDragonChampionSummary[]>(
    `${CDRAGON_BASE}/champion-summary.json`,
  )
  const validChampions = champions.filter((c) => c.id > 0)
  console.log(`API returned ${validChampions.length} champions\n`)

  // 3. Match local dirs to API data and fetch skin info
  const catalog: CatalogEntry[] = []
  const matched = validChampions.filter((c) => localAliases.has(c.alias.toLowerCase()))
  console.log(`${matched.length} champions matched with local assets\n`)

  await pooled(matched, 5, async (champ, i) => {
    const alias = champ.alias.toLowerCase()
    try {
      // Fetch detailed champion data (with skins)
      const data = await fetchJSON<CDragonChampionData>(
        `${CDRAGON_BASE}/champions/${champ.id}.json`,
      )

      // List local GLB files
      const files = await readdir(join(ASSETS_DIR, alias))
      const localSkinIds = new Set(
        files.filter((f) => f.endsWith('.glb')).map((f) => f.replace('.glb', '')),
      )

      // Only include skins that exist locally
      const skins: CatalogSkin[] = data.skins
        .filter((s) => localSkinIds.has(String(s.id)))
        .map((s) => ({
          id: String(s.id),
          name: s.isBase ? data.name : s.name || `Skin ${s.id}`,
          isBase: s.isBase,
        }))

      if (skins.length > 0) {
        catalog.push({
          alias,
          name: data.name,
          id: data.id,
          skins,
        })
        console.log(`  [${i + 1}/${matched.length}] ${data.name}: ${skins.length} skins`)
      }
    } catch (err) {
      console.warn(`  [${i + 1}/${matched.length}] Failed to fetch ${champ.name}: ${err}`)
    }
  })

  // Sort by name
  catalog.sort((a, b) => a.name.localeCompare(b.name))

  console.log(`\nGenerating catalog with ${catalog.length} champions...\n`)

  // 4. Generate TypeScript file
  const lines: string[] = []
  lines.push('// Auto-generated by scripts/generate-champion-catalog.ts')
  lines.push('// Do not edit manually.')
  lines.push('')
  lines.push('export interface ChampionSkin {')
  lines.push('  id: string')
  lines.push('  name: string')
  lines.push('  isBase: boolean')
  lines.push('}')
  lines.push('')
  lines.push('export interface ChampionCatalogEntry {')
  lines.push('  alias: string')
  lines.push('  name: string')
  lines.push('  id: number')
  lines.push('  skins: ChampionSkin[]')
  lines.push('}')
  lines.push('')
  lines.push('export const CHAMPION_CATALOG: Record<string, ChampionCatalogEntry> = {')

  for (const entry of catalog) {
    const skinsStr = entry.skins
      .map((s) => `    { id: '${s.id}', name: ${JSON.stringify(s.name)}, isBase: ${s.isBase} },`)
      .join('\n')

    lines.push(`  '${entry.alias}': {`)
    lines.push(`    alias: '${entry.alias}',`)
    lines.push(`    name: ${JSON.stringify(entry.name)},`)
    lines.push(`    id: ${entry.id},`)
    lines.push(`    skins: [`)
    lines.push(skinsStr)
    lines.push(`    ],`)
    lines.push(`  },`)
  }

  lines.push('}')
  lines.push('')
  lines.push('/** Sorted list of champion aliases */')
  lines.push('export const CHAMPION_LIST: string[] = Object.keys(CHAMPION_CATALOG)')
  lines.push('')
  lines.push('/** Get the base (default) skin ID for a champion */')
  lines.push('export function getBaseSkinId(alias: string): string | undefined {')
  lines.push('  const entry = CHAMPION_CATALOG[alias]')
  lines.push('  if (!entry) return undefined')
  lines.push('  const base = entry.skins.find((s) => s.isBase)')
  lines.push('  return base?.id ?? entry.skins[0]?.id')
  lines.push('}')
  lines.push('')

  await Bun.write(OUTPUT_FILE, lines.join('\n'))
  console.log(`Wrote ${OUTPUT_FILE}`)
  console.log(
    `  ${catalog.length} champions, ${catalog.reduce((sum, c) => sum + c.skins.length, 0)} total skins`,
  )
}

main().catch((err) => {
  console.error('Fatal error:', err)
  process.exit(1)
})
